### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by Atraxus** [Atraxus/dit#8]
I will add the CI tests once PR #2 is merged.

**Comment by Atraxus** [comment]
@lukas-code, there were some more things you suggested apart from just running it for the cli test. I should've written them down ^^
Could you tell me what commands you wanted the cli to run?

**Comment by Atraxus** [comment]
Do we want both windows and linux?

**Comment by lukas-code** [comment]
I think we should run at least
* `cargo build`, `cargo build --release`
* `cargo test`, `cargo test --release`
* `cargo clippy`
* `cargo fmt --check`

preferably on all combinations of linux + windows / rust stable + rust nightly

**Comment by lukas-code** [comment]
Also CLI = command line interface, CI = continuous integration

Mit dem https://github.com/Atraxus/dit/labels/A-cli label meinte ich das was der user dann bei sich in die Kommandozeile schreibt.

**Comment by lukas-code** [comment]
If you can also host the output of `cargo doc` on GitHub pages like [this](https://lukas-code.github.io/dit/dit_core/index.html), that would be super cool and allow searching all dependencies at once.

**Comment by Atraxus** [comment]
I will look into it 👍
